### PR TITLE
Path generation: don't move to 0, 0 when not necessary

### LINKED ISSUE #128: iOS12 regression on pathsFromSVGString
Hello, 

I am getting a regression when creating a CGPath from a SVG string with iOS12 (with iOS11 it works fine). It can be reproduced with the following data/code (a simple square).

Here's the svg:
```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
 "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="512.000000pt" height="512.000000pt" viewBox="0 0 512.000000 512.000000"
 preserveAspectRatio="xMidYMid meet">
<metadata>
</metadata>
<g transform="translate(0.000000,512.000000) scale(1.000000,1.000000)"
fill="#000000" stroke="none">
<path d="M21 256 l0 -235 235 0 235 0 0 235 0 235 -235 0 -235 0 0 -235z"/>
</g>
</svg>
```

### Steps to reproduce the issue

```objc
    NSString* svg = @"<?xml version=\"1.0\" standalone=\"no\"?> <!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 20010904//EN\" \"http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd\"> <svg version=\"1.0\" xmlns=\"http://www.w3.org/2000/svg\" width=\"512.000000pt\" height=\"512.000000pt\" viewBox=\"0 0 512.000000 512.000000\" preserveAspectRatio=\"xMidYMid meet\"> <metadata> </metadata> <g transform=\"translate(0.000000,512.000000) scale(1.000000,1.000000)\" fill=\"#000000\" stroke=\"none\"> <path d=\"M21 256 l0 -235 235 0 235 0 0 235 0 235 -235 0 -235 0 0 -235z\"/> </g> </svg>";
    NSArray *paths = [SVGBezierPath pathsFromSVGString:svg];
    SVGBezierPath *firstPath = paths.firstObject;
    UIBezierPath *path = [UIBezierPath bezierPathWithCGPath:firstPath.CGPath];
    CGRect pathBounds = CGPathGetPathBoundingBox(path.CGPath);
    NSLog(@"PATH BOUNDS: %@", NSStringFromCGRect(pathBounds));
```

### Has my issue been reported? 

No.

### Results

With iOS 11 
PATH BOUNDS: {{21, 21}, {470, 470}}

With iOS 12
PATH BOUNDS: {{0, 0}, {491, 491}}
 
If I dump the control points I can see that under iOS12 there's the origin added as control point while this is not happening under iOS11:

iOS12
```
  Bounds: {{0, 0}, {491, 491}}
  Control Point Bounds: {{0, 0}, {491, 491}}
    0.000000 0.000000 moveto
    21.000000 256.000000 moveto
    21.000000 21.000000 lineto
    256.000000 21.000000 lineto
    491.000000 21.000000 lineto
    491.000000 256.000000 lineto
    491.000000 491.000000 lineto
    256.000000 491.000000 lineto
    21.000000 491.000000 lineto
    21.000000 256.000000 lineto
    closepath
```
iOS11
```
Bounds: {{21, 21}, {470, 470}}
  Control Point Bounds: {{21, 21}, {470, 470}}
    21.000000 256.000000 moveto
    21.000000 21.000000 lineto
    256.000000 21.000000 lineto
    491.000000 21.000000 lineto
    491.000000 256.000000 lineto
    491.000000 491.000000 lineto
    256.000000 491.000000 lineto
    21.000000 491.000000 lineto
    21.000000 256.000000 lineto
    closepath
```

### Specifications

  - PocketSVG Version: 2.4.0
  - Xcode Version: 10.0 GM
  - iOS/macOS Version: iOS 12 GM

Thanks for any feedback,
Libe

### PR DESCRIPTION
**Pull request by noahsark769**
Fixes #128 

There was an issue with iOS 12 where previously, CGPath would collapse two consecutive move statements into one. This is no longer the case on iOS 12, so paths which start with move commands to points other than the origin ended up with incorrect bounding boxes, because we started every path with a `moveto 0, 0` in order to set up paths whose first command was not a move.

After this diff, we no longer move to 0, 0 if we don't need to. Instead, when appending each command, we check if we need to append a `moveto 0, 0` first. We need to do this check in every command parsing method except `appendMoveTo`, but I figured this approach would be more robust than trying to look at the first command and see if it was a move.

I also wrote a test which exposed the iOS 12 regression.

@fjolnir feel free to review whenever :)

### CODE REVIEW

**Comment by nicolasmuller** [comment]
much better :)

**Comment by fjolnir** [comment]
Wouldn't it be easier to just look at the first element in `pathDefinitionParser::parse()` and add a a moveto if the path isn't already prepended by it?

Like so:
```objc
_cmd = [cmdBuf characterAtIndex:0];
if (![_cmd.uppercaseString isEqualToString:@"M"] && CGPathIsEmpty(_path)) {
    // Workaround for https://github.com/pocketsvg/PocketSVG/issues/128
    CGPathMoveToPoint(_path, NULL, 0, 0) 
}
switch(_cmd) {
```

**Comment by noahsark769** [comment]
Note that we could also use some sort of boolean like `isFirstCommand` which would be set to false at the end of the loop, but I felt this was a little bit hacky. Also, the method currently in the PR opens it up so that every type of command can choose whether it wants to add a `moveto 0, 0` if it's the first command, which I felt was a little nicer.

Happy to use the `isFirstCommand` if you feel strongly about it though, just happen to fix this any way we can :)

**Comment by arielelkin** [comment]
@fjolnir any objections to merging this?

**Comment by fjolnir** [comment]
If the path is empty, wouldn't the current command be the first?

**Comment by arielelkin** [comment]
I think so, which is what `appendMoveToOriginIfNeeded` would be for, right @noahsark769 ?

**Comment by noahsark769** [comment]
@fjolnir @arielelkin sorry for the delay on getting back to this! I did some digging at it and I realized I didn't see the additional `CGPathIsEmpty` in @fjolnir's example above. I think that example is much cleaner, and still passes the test, so I'll add it presently.

**Comment by noahsark769** [comment]
We should be good to go on this! Let me know if I can clarify anything further 👍

File: SVGEngine.mm [hunk 1]
```diff
@@ -521,6 +520,12 @@ @interface SVGAttributeSet () {
 #endif
         _lastCmd = _cmd;
         _cmd = [cmdBuf characterAtIndex:0];
+
+        if (![[cmdBuf substringToIndex:1].uppercaseString isEqualToString:@"M"] && CGPathIsEmpty(_path)) {
```
Comment (fjolnir) [inline SVGEngine.mm]: I'd prefer `[cmdBuf.uppercaseString hasPrefix:@"M"]`

**Comment by arielelkin** [comment]
Thanks @noahsark769 

You've also been credited in the CHANGELOG  😄

File: SVGEngine.mm (hunk 1 above)
Comment (arielelkin) [reply SVGEngine.mm]: see https://github.com/pocketsvg/PocketSVG/pull/141
