### PR TITLE
Use svgAttributes when generating SVGRepresentation for SVGBezierPath

### LINKED ISSUE #112: Attributes are missing when using -[SVGBezierPath SVGRepresentation]
### Steps to reproduce the issue

  1. Create a `SVGBezierPath` and set some SVG attributes 

```Swift
        let attributes: [String: Any] = [
            "stroke": "black",
            "stroke-width": "2",
            "fill": "transparent"
        ]
        let bezierPath = SVGBezierPath().settingSVGAttributes(attributes)
```
  
  2. Create and print SVG representation of the path

```Swift
let representation = bezierPath.svgRepresentation
print(representation)
```

**Expected result**: `path` has the specified attributes (stroke, fill, stroke-width) in the generated SVG
```XML
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0">
  <path stroke="black" fill="transparent" stroke-width="2.0" d=""/>

</svg>
```

**Actual result**: the attributes are missing
```XML
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0">
  <path d=""/>

</svg>
```

### Has my issue been reported? 

No

### Specifications

  - PocketSVG Version: master (afd002b)
  - Xcode Version: 9.2
  - iOS/macOS Version: iOS 11.2

### PR DESCRIPTION
**Pull request by mciuba**
Fixes #112

### CODE REVIEW

File: SVGBezierPath.mm [hunk 1]
```diff
@@ -72,8 +72,11 @@ + (NSArray *)pathsFromSVGString:(NSString * const)svgString
 
 - (NSString *)SVGRepresentation
 {
-    return SVGStringFromCGPaths(@[(__bridge id)self.CGPath], nil);
+    SVGMutableAttributeSet *attributes = [SVGMutableAttributeSet new];
+    [attributes setAttributes:self.svgAttributes forPath:self.CGPath];
+    return SVGStringFromCGPaths(@[(__bridge id)self.CGPath], [attributes copy]);
```
Comment (fjolnir) [inline SVGBezierPath.mm]: Wouldn't `return SVGStringFromCGPaths(@[(__bridge id)self.CGPath], self.attributes)` work?

Comment (mciuba) [reply SVGBezierPath.mm]: Unfortunately, it wouldn't work because `self.attributes` is a `NSDictionary<NSString*, id>` and  `SVGStringFromCGPaths` expects `SVGAttributeSet` as the second parameter.

Comment (fjolnir) [reply SVGBezierPath.mm]: Ah, ok. Sorry. It's been a little while since I worked on this :)
Then apart from the copy being unnecessary, it looks good!

**Comment by mciuba** [comment]
@fjolnir Fixed. Good point, defensive copy is not needed in this case.  It's been a little while since I worked on Objective-C ;)
